{{- if .Values.ingress.enabled -}}
{{- $fullName := include "baget.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "baget.name" . }}
    helm.sh/chart: {{ include "baget.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
{{- if .Values.service.commonName }}
    - {{ template "hostname" .Values.service.commonName }}
{{- end }}
    - {{ template "hostname" .Values.service.url }}
    secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "baget.fullname" .)) }}
{{- end }}
  rules:
    - host: {{ template "hostname" .Values.service.url }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
{{- if .Values.service.commonName }}
    - host: {{ template "hostname" .Values.service.commonName }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ $fullName }}
            servicePort: http
{{- end }}
{{- end }}
